---
language: csharp

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1

before_install:
  - sudo apt-get install nunit-console
script:
  - dotnet restore
  - dotnet build src/DotLiquid/project.json --configuration Release --framework netstandard1.3
  - dotnet build src/DotLiquid.Website/project.json --configuration Release --framework netcoreapp1.0
  - dotnet build src/DotLiquid.Tests/project.json --configuration Release --framework netcoreapp1.0
  - dotnet build src/DotLiquid.Website.Tests/project.json --configuration Release --framework netcoreapp1.0
  - dotnet test src/DotLiquid.Tests --framework netcoreapp1.0
  - dotnet test src/DotLiquid.Website.Tests --framework netcoreapp1.0
 